ALTER TABLE usuarios MODIFY rol ENUM('DIURNO','TARDE','DIRECTORA','SUPER','SUBDIRECTOR') NOT NULL DEFAULT 'DIURNO';
DELETE FROM usuarios WHERE rol = 'SUPER';
ALTER TABLE usuarios MODIFY rol ENUM('DIURNO','TARDE','DIRECTORA','SUBDIRECTOR') NOT NULL DEFAULT 'DIURNO';